SELECT 
    A.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY, 
    SUM(S.TS * B.PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS TS
    FROM BOOK_SALES 
    WHERE SALES_DATE >= DATE '2022-01-01' 
        AND SALES_DATE < DATE '2022-02-01'
    GROUP BY BOOK_ID ) S 
ON B.BOOK_ID = S.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC