SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S
    JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE SALES_DATE >= DATE '2022-01-01'
    AND SALES_DATE < DATE '2022-02-01'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;