SELECT CART_ID
FROM (
    SELECT
        CART_ID,
        MAX(CASE NAME WHEN 'Milk' THEN 1 ELSE 0 END) AS M,
        MAX(CASE NAME WHEN 'Yogurt' THEN 1 ELSE 0 END) AS Y
    FROM CART_PRODUCTS 
    GROUP BY CART_ID  
)
WHERE M = 1 AND Y = 1
ORDER BY CART_ID;