SELECT PRODUCT_CODE, SUM(SALE) AS SALES
FROM (
    SELECT P.PRODUCT_CODE, (P.PRICE * O.SALES_AMOUNT) AS SALE
    FROM PRODUCT P JOIN OFFLINE_SALE O
    ON P.PRODUCT_ID = O.PRODUCT_ID)
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;
