SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE,
       PRODUCT_ID,
       USER_ID,
       SALES_AMOUNT
FROM (
    SELECT USER_ID, 
           PRODUCT_ID,     
           SALES_AMOUNT,
           SALES_DATE  
    FROM ONLINE_SALE
    
    UNION ALL
    
    SELECT  NULL AS USER_ID, 
            PRODUCT_ID,     
            SALES_AMOUNT,
            SALES_DATE  
     FROM OFFLINE_SALE
)
WHERE SALES_DATE >= DATE '2022-03-01'
    AND SALES_DATE < DATE '2022-04-01'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;