
SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
     EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    COUNT(DISTINCT(USER_ID)) AS PURCHASED_USERS,
    ROUND(
           COUNT(DISTINCT USER_ID) /
           (
               SELECT COUNT(*)
               FROM USER_INFO
               WHERE JOINED >= DATE '2021-01-01'
                 AND JOINED <  DATE '2022-01-01'
           ),
           1
       ) AS PUCHASED_RATIO
FROM ONLINE_SALE 
WHERE USER_ID IN 
(
    SELECT USER_ID
    FROM USER_INFO
    WHERE DATE '2021-01-01' <= JOINED AND JOINED < DATE '2022-01-01'
)
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC