WITH USERS_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED >= DATE '2021-01-01'
        AND JOINED < DATE '2022-01-01'
)
SELECT  EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
        EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
        COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
        ROUND(
            COUNT(DISTINCT O.USER_ID) /
            (SELECT COUNT(*) FROM USERS_2021),
            1
       ) AS PUCHASED_RATIO
FROM ONLINE_SALE O
JOIN USERS_2021 U
    ON O.USER_ID = U.USER_ID
GROUP BY EXTRACT(YEAR FROM O.SALES_DATE), 
        EXTRACT(MONTH FROM O.SALES_DATE)
ORDER BY YEAR, MONTH;