WITH RECURSIVE GEN AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GEN G
    ON G.ID = E.PARENT_ID
) 
SELECT COUNT(*) AS COUNT, G.GENERATION
FROM GEN G
LEFT JOIN ECOLI_DATA E
ON G.ID = E.PARENT_ID
WHERE E.PARENT_ID IS NULL 
GROUP BY G.GENERATION
ORDER BY G.GENERATION