SELECT NAME, DATETIME
FROM (
    SELECT I.NAME AS NAME, I.DATETIME AS DATETIME
    FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    WHERE O.DATETIME IS NULL
    ORDER BY I.DATETIME
     )
WHERE ROWNUM <= 3;