WITH HOURS AS (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
)
SELECT H.HOUR,
       COUNT(A.DATETIME) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS A
    ON H.HOUR = TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24'))
GROUP BY H.HOUR
ORDER BY H.HOUR;
