SELECT HOUR, COUNT(*) AS COUNT
FROM (
    SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
    FROM ANIMAL_OUTS
    WHERE TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) BETWEEN 9 AND 20
    )
GROUP BY HOUR
ORDER BY HOUR;
