SELECT P.MEMBER_NAME, 
       R.REVIEW_TEXT,
       TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM REST_REVIEW R
    JOIN MEMBER_PROFILE P
    ON R.MEMBER_ID = P.MEMBER_ID
WHERE R.MEMBER_ID = (SELECT MEMBER_ID
                    FROM REST_REVIEW
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(*) DESC
                    FETCH FIRST 1 ROW ONLY)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;
