WITH RENTAL AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= DATE '2022-08-01'
      AND START_DATE <  DATE '2022-11-01'
)
SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH,
       CAR_ID, COUNT(*) AS RECORDS
FROM RENTAL
WHERE CAR_ID IN ( 
    SELECT CAR_ID
    FROM RENTAL
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
ORDER BY MONTH, CAR_ID DESC;