SELECT B.TITLE, 
    B.BOARD_ID, 
    R.REPLY_ID, 
    R.WRITER_ID, 
    R.CONTENTS, 
    TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD B 
JOIN USED_GOODS_REPLY R
ON B.BOARD_ID = R.BOARD_ID
WHERE DATE '2022-10-01' <= B.CREATED_DATE
    AND B.CREATED_DATE < DATE '2022-11-01'
ORDER BY CREATED_DATE ASC, TITLE ASC;