SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES S
    ON B.BOOK_ID = S.BOOK_ID
WHERE DATE '2022-01-01' <= S.SALES_DATE
    AND S.SALES_DATE < DATE '2022-02-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;
